### ISSUE TITLE
The sanity part needs @sanity/cli as a dependency

### ISSUE THREAD

**Issue by hexjelly** [oslopride/opbf#1]
In order to build the site, the sanity cli is assumed to be installed. Hence running this in a CI environment will fail since the sanity command does not exist. 

Suggest adding @sanity/cli as a dependency :)
Alternatively the build command could use the `npx` command or similar, but I think this is a worse solution

**Comment by Camorte** [comment]
Issue fixed with commit 1b60ed70d7612607551158b784f2e80f4732d504
