### ISSUE TITLE
IMPR UI - Text styling

### ISSUE THREAD

**Issue by lovisegit** [oslopride/opbf#5]
**Subtitle on front page hero:**
Change to
  Font-weight:700;
  Font-size: 24px; (18px on mobile)

<img width="1656" alt="Skjermbilde 2021-11-14 kl  14 35 11" src="https://user-images.githubusercontent.com/93185620/141683514-aa4f9d70-1f18-4a66-a341-0b77015f6e9e.png">

Text-section below hero:

Change to:
Font-size: 24px
Line-height: 36px;

The text-box is also very narrow on smaller screens. Should have a max-width of 800px with a 24px margin left and right. 
Maybe remove this: max-width: clamp(20rem, 60%, 40rem); 
??
<img width="1485" alt="Skjermbilde 2021-11-14 kl  14 41 51" src="https://user-images.githubusercontent.com/93185620/141683660-632c0466-d2a8-48b4-8bbf-a79ab98f99d1.png">

**Comment by Camorte** [comment]
Issue fixed with commit 690cd2b01a04c90e1b6e54b8849db85826fe8504
