### ISSUE TITLE
Change to new logo

### ISSUE THREAD

**Issue by lovisegit** [oslopride/opbf#6]
![OPBF Hvit](https://user-images.githubusercontent.com/93185620/141683740-2c798ce8-fe3b-48e4-aa35-c5ffe89fd19f.png)

Also sent to Carlo on slack.

**Comment by Camorte** [comment]
Issue fixed with commits: e19b2c657bd44c1e552d46c08b4ce5e228ddb879 and 3d6243d20559966e1315fadd6662981525948e85
