### ISSUE TITLE
/Program - Change margins and icon

### ISSUE THREAD

**Issue by lovisegit** [oslopride/opbf#7]
Margins around the content is a bit much.

Mobile:
Margin: 3rem auto 3rem;

Desktop: 
Margin: 4rem auto 4rem;

<img width="1156" alt="Skjermbilde 2021-11-14 kl  14 53 55" src="https://user-images.githubusercontent.com/93185620/141684151-4eaefbe7-fc9a-4da0-a65f-58ceb6578165.png">

Also the icon used on the button on hero is not the same as on the oslopride.no site. 

Use this one: 
<img width="391" alt="Skjermbilde 2021-11-14 kl  14 51 19" src="https://user-images.githubusercontent.com/93185620/141684068-95673c54-26ca-455d-bfbb-15aeb58f65a9.png">

SVG:
[Forward.svg.zip](https://github.com/oslopride/opbf/files/7533849/Forward.svg.zip)

**Comment by Camorte** [comment]
Issue fixed with commits: 93d823817d4b1c8aceb69fde2667058ed100920a and fbe35d0fce63be503bbd4409d231a249c48bee92
